app = "empathia-backend"
primary_region = "mia"

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "production"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[http_service.concurrency]
type = "requests"
hard_limit = 250
soft_limit = 200

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1